---
- name: Run cte cluster container using latest image
  hosts: cte_sub_match_engine
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: cte_sub_match_engine
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            cte_sub_match_engine:
              image: highperformancecomputing/cte:latest
              container_name: cte_sub_match_engine
              environment:
                HOST: cte_sub_match_engine
                SEEDS: cte_match_engine:4445
                ROLE: normal_host
                APP: /bin/match_engine_server
                APP_ARGS: --symbol_id_list="51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100" --log_file=/tmp/log/cte_sub_match_engine.log --log_level=info
              network_mode: host
              extra_hosts:
                - "cte_match_engine:172.30.28.10"
                - "cte_sub_match_engine:172.30.28.3"
              volumes:
                - /tmp/log:/tmp/log
    - assert:
        that:
          - "cte_sub_match_engine.cte_sub_match_engine.state.running"