---
- name: Run cte cluster container using latest image
  hosts: akka_te_match_engine
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: akka_te_match_engine
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            akka_te_match_engine:
              image: highperformancecomputing/akka-te:latest
              container_name: akka_te_match_engine
              environment:
                APP_CONFIG_FILE: "./gateway.conf"
                HOST_NAME: "akkagateway"
                SYMBOL_IDS: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25"
              network_mode: host
              extra_hosts:
                - "akkagateway:172.30.28.12"
                - "akkanode:172.30.28.31"
              volumes:
                - /tmp/log:/tmp/log
    - assert:
        that:
          - "akka_te_match_engine.akka_te_match_engine.state.running"