---
- name: Run cte cluster container using latest image
  hosts: akka_te_sub_match_engine
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: akka_te_sub_match_engine
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            akka_te_sub_match_engine:
              image: highperformancecomputing/akka-te:latest
              container_name: akka_te_sub_match_engine
              environment:
                APP_CONFIG_FILE: "./node.conf"
                HOST_NAME: "akkanode"
                SYMBOL_IDS: "26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50"
              network_mode: host
              extra_hosts:
                - "akkagateway:172.30.28.12"
                - "akkanode:172.30.28.31"
              volumes:
                - /tmp/log:/tmp/log
    - assert:
        that:
          - "akka_te_sub_match_engine.akka_te_sub_match_engine.state.running"